name: Satis
on:
  push:
jobs:
  build_dependencies:
    name: Build dependencies
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
    steps:
    - name: Trigger dependencies build 
      run: |
        json="{\"ref\": \"main\", \"inputs\": {\"repository\": \"${{ github.repository }}\"}}"
        curl -XPOST -u "$GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" "$GITHUB_API_URL/repos/batiweb-group/repositories-dependencies/actions/workflows/update.yml/dispatches" --data "$json"
